"""Generate the living architecture diagram (docs/ARCHITECTURE/ARCHITECTURE.md).

Introspects the actual codebase — never a hand-drawn picture, never aspiration:
  - the `@mcp.tool()` inventory of both MCP servers (parsed from server.py source), and
  - the pinned worker model of every `.claude/agents/*.md` subagent (parsed from its
    YAML frontmatter `model:` field).

The four canonical ingestion/write paths and the "judgment never lives in MCP" boundary
are a small explicit structural literal below (the shape doesn't change per-run; the tool
and agent inventories do, so those are read from disk on every run).

Deterministic: no timestamps, no randomness; all lists are sorted. Re-running against
unchanged source reproduces this file byte-for-byte.

Regenerate at every phase seal:
    .venv\\Scripts\\python.exe scripts/gen_architecture_diagram.py
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOL_RE = re.compile(r"@mcp\.tool\(\)\s*\n\s*async def (\w+)\(")
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
NAME_RE = re.compile(r"^name:\s*(\S+)", re.MULTILINE)
MODEL_RE = re.compile(r"^model:\s*(\S+)", re.MULTILINE)

SERVERS = {
    "chimera-papers": REPO_ROOT / "mcp-servers" / "chimera-papers" / "server.py",
    "chimera-vault": REPO_ROOT / "mcp-servers" / "chimera-vault" / "server.py",
}

# The canonical four ingestion/write paths — structural shape, not tool/model inventory
# (that part IS introspected above). See phase-L.B sprint scope for the authoritative statement.
INGESTION_PATHS = [
    ("scout_batch", "daily_paper_pipeline (batch)", "inbox/<verdict>/", "scout"),
    ("scout_single", "ingest_paper (single)", "inbox/<verdict>/", "scout"),
    (
        "deep_read",
        "chimera-deep-extract skill -> Sonnet subagent -> stage_deep_read_node",
        "docs/staging/",
        "deep_read",
    ),
    ("ascension", "ascend_node (requires chimera_tier=deep_read)", "Knowledge/ (SOLE writer)", "-"),
]


def parse_tools(server_path: Path) -> list[str]:
    text = server_path.read_text(encoding="utf-8")
    return sorted(TOOL_RE.findall(text))


def parse_agent_model(agent_path: Path) -> tuple[str, str] | None:
    text = agent_path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    frontmatter = match.group(1)
    name_match = NAME_RE.search(frontmatter)
    model_match = MODEL_RE.search(frontmatter)
    if not name_match or not model_match:
        return None
    return name_match.group(1), model_match.group(1)


def render(tools_by_server: dict[str, list[str]], agents: list[tuple[str, str]]) -> str:
    lines: list[str] = []
    lines.append("# Chimera Lite — Architecture (generated)")
    lines.append("")
    lines.append(
        "Generated by `scripts/gen_architecture_diagram.py`. Do not hand-edit — regenerate "
        "at every phase seal. Describes actual code as it stands; never aspiration."
    )
    lines.append("")
    lines.append("## MCP tool inventory")
    lines.append("")
    for server_name in sorted(tools_by_server):
        lines.append(f"### {server_name}")
        lines.append("")
        for tool_name in tools_by_server[server_name]:
            lines.append(f"- `{tool_name}`")
        lines.append("")
    lines.append("## Subagent -> model pins")
    lines.append("")
    lines.append("| agent | model |")
    lines.append("|---|---|")
    for agent_name, model in agents:
        lines.append(f"| {agent_name} | {model} |")
    lines.append("")
    lines.append("## Ingestion / write paths")
    lines.append("")
    lines.append(
        "Judgment is externalized out of the MCP layer entirely (Phase L.B): the MCP servers "
        "make NO LLM call. Triage judgment = `chimera-paper-triager` (Haiku); deep-read "
        "judgment = `chimera-deep-extractor` (Sonnet). Both are Claude Code subagents, never "
        "MCP-internal."
    )
    lines.append("")
    lines.append("```mermaid")
    lines.append("flowchart TD")
    lines.append('    subgraph judgment["judgment = Claude Code subagents, never MCP"]')
    lines.append('        triager["chimera-paper-triager (haiku)"]')
    lines.append('        extractor["chimera-deep-extractor (sonnet)"]')
    lines.append("    end")
    lines.append("")
    for path_id, step, dest, tier in INGESTION_PATHS:
        label = step if tier == "-" else f"{step} [chimera_tier={tier}]"
        lines.append(f'    {path_id}["{label}"] --> {path_id}_dest["{dest}"]')
    lines.append("    scout_batch -.-> triager")
    lines.append("    scout_single -.-> triager")
    lines.append("    deep_read -.-> extractor")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    tools_by_server = {name: parse_tools(path) for name, path in SERVERS.items()}
    agents_dir = REPO_ROOT / ".claude" / "agents"
    agents: list[tuple[str, str]] = []
    for agent_path in sorted(agents_dir.glob("*.md")):
        parsed = parse_agent_model(agent_path)
        if parsed is not None:
            agents.append(parsed)
    agents.sort(key=lambda pair: pair[0])

    out_path = REPO_ROOT / "docs" / "ARCHITECTURE" / "ARCHITECTURE.md"
    out_path.write_text(render(tools_by_server, agents), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
